import json
from openai import OpenAI
import pandas as pd
import requests
import streamlit as st
import time

st.set_page_config(page_title="Melodi | Create Bake-off", page_icon='melodi_transparent.png', initial_sidebar_state='expanded',)

with st.sidebar:
    melodi_api_key = st.text_input("Melodi API Key", type="password")

def create_experiment(experiment_name, experiment_instructions, comparisons):
    api_key = melodi_api_key
    base_url = "https://app.melodi.fyi/api/external/experiments?apiKey="
    url = base_url + api_key
    headers = {"Content-Type": "application/json"}

    # Data payload for the POST request
    data = {
        "experiment": {
            "name": experiment_name,
            "instructions": experiment_instructions
        },
        "comparisons": comparisons
    }

    # Make the POST request
    response = requests.post(url, headers=headers, data=json.dumps(data))

    return response
st.image('melodi_transparent.png', width=70)
st.title("Create a Melodi Bake-off Evaluation")
st.caption("Ideal for copy/pasting directly from ChatGPT. Enter your Melodi API key in the sidebar to begin.")


experiment_name = st.text_input(
        "Experiment name (reviewers won't see this)",
    )

experiment_instructions = st.text_input(
        "Instructions for reviewers",
    )

if 'disabled' not in st.session_state:
    st.session_state['disabled'] = False

tab1, tab2 = st.tabs(["Manual Entry", "CSV Upload"])

with tab1:
    if 'disabled' not in st.session_state:
        st.session_state['disabled'] = False

    col1, col2 = st.columns(2)

    if 'help' not in st.session_state:
        st.session_state.help = "Reviewers won't see this"

    with col1:
        prompt_1 = st.text_input(
            "Model or Prompt Name",
            key="placeholder",
            value="Original Prompt",
            disabled=st.session_state.disabled,
            help="Names can't be updated if data is present in the table."
        )

    with col2:
        prompt_2 = st.text_input(
            "Model or Prompt Name (Comparison)",
            value="New Prompt",
            disabled=st.session_state.disabled,
            help="Names can't be updated if data is present in the table."
        )



    df = pd.DataFrame(columns=[prompt_1, prompt_2])

    config = {
        prompt_1 : st.column_config.TextColumn(f"Generated by {prompt_1}", width='large', required=True),
        prompt_2 : st.column_config.TextColumn(f" Generated by {prompt_2}", width='large', required=True),
    }


    


    samples = st.data_editor(df, column_config = config, num_rows='dynamic')


    if len(samples.index) > 0:
        st.session_state.disabled = True
        st.session_state.help = "Prompt names can't be updated when data is present in the table."



with tab2:
    uploaded_file = st.file_uploader(label='A header row must be provided in the file for Prompt Version. Column 1 should contain responses generated from Prompt 1. Column 2 should contain resposnes generated from Prompt 2. ', type=['csv'])
    if uploaded_file is not None:
        st.session_state['file'] = True
        file = pd.read_csv(uploaded_file,header=0)
        samples = file.iloc[:,0:2]
        prompt_1, prompt_2 = samples.columns.tolist()
        styled_df = samples.style.set_properties(**{'background-color': '#f7fafc',})
        st.dataframe(styled_df,hide_index=True)

if st.button('Create Experiment'):
    comparisons = []
    for index, sample in samples.iterrows(): # Loop through rows with iterrows()
        
        comparisons.append({"samples":[
            {"response": sample[prompt_1],"promptLabel": prompt_1}, 
            {"response": sample[prompt_2], "promptLabel": prompt_2} 
        ]})
    
    
    melodi_response = create_experiment(experiment_name, experiment_instructions, comparisons)
    if melodi_response.status_code == 200:
        res = melodi_response.json()
        feedback_url = res.get('feedbackUrl')
        results_url = res.get('resultsUrl')
        
        st.write(f"Feedback URL: {feedback_url}")
        st.write(f"Results URL: {results_url}")

    else:
        response_content = json.loads(melodi_response.content)
        st.write(f"Failed to create experiment. {response_content}")

